package com.zbsp.wepaysp.common.constant;

/***
 * 微信支付银行类型枚举
 * 
 * @author 孟郑宏
 */
public enum WxPayBank {
    
    ICBC_DEBIT("ICBC_DEBIT", "工商银行(借记卡)"),
    ICBC_CREDIT("ICBC_CREDIT", "工商银行(信用卡)"),
    ABC_DEBIT("ABC_DEBIT", "农业银行(借记卡)"),
    ABC_CREDIT("ABC_CREDIT", "农业银行(信用卡)"),
    PSBC_DEBIT("PSBC_DEBIT", "邮政储蓄银行(借记卡)"),
    PSBC_CREDIT("PSBC_CREDIT", "邮政储蓄银行(信用卡)"), 
    CCB_DEBIT("CCB_DEBIT", "建设银行(借记卡)"), 
    CCB_CREDIT("CCB_CREDIT", "建设银行(信用卡)"),
    CMB_DEBIT("CMB_DEBIT", "招商银行(借记卡)"),
    CMB_CREDIT("CMB_CREDIT", "招商银行(信用卡)"),
    BOC_DEBIT("BOC_DEBIT", "中国银行(借记卡)"), 
    BOC_CREDIT("BOC_CREDIT", "中国银行(信用卡)"), 
    COMM_DEBIT("COMM_DEBIT", "交通银行(借记卡)"), 
    SPDB_DEBIT("SPDB_DEBIT", "浦发银行(借记卡)"), 
    SPDB_CREDIT("SPDB_CREDIT", "浦发银行(信用卡)"), 
    GDB_DEBIT("GDB_DEBIT", "广发银行(借记卡)"), 
    GDB_CREDIT("GDB_CREDIT", "广发银行(信用卡)"), 
    CMBC_DEBIT("CMBC_DEBIT", "民生银行(借记卡)"), 
    CMBC_CREDIT("CMBC_CREDIT", "民生银行(信用卡)"), 
    PAB_DEBIT("PAB_DEBIT", "平安银行(借记卡)"), 
    PAB_CREDIT("PAB_CREDIT", "平安银行(信用卡)"), 
    CEB_DEBIT("CEB_DEBIT", "光大银行(借记卡)"), 
    CEB_CREDIT("CEB_CREDIT", "光大银行(信用卡)"), 
    CIB_DEBIT("CIB_DEBIT", "兴业银行(借记卡)"), 
    CIB_CREDIT("CIB_CREDIT", "兴业银行(信用卡)"), 
    CITIC_DEBIT("CITIC_DEBIT", "中信银行(借记卡)"), 
    CITIC_CREDIT("CITIC_CREDIT", "中信银行(信用卡)"), 
    BOSH_DEBIT("BOSH_DEBIT", "上海银行(借记卡)"), 
    BOSH_CREDIT("BOSH_CREDIT", "上海银行(信用卡)"), 
    CRB_DEBIT("CRB_DEBIT", "华润银行(借记卡)"), 
    HZB_DEBIT("HZB_DEBIT", "杭州银行(借记卡)"), 
    HZB_CREDIT("HZB_CREDIT", "杭州银行(信用卡)"), 
    BSB_DEBIT("BSB_DEBIT", "包商银行(借记卡)"), 
    BSB_CREDIT("BSB_CREDIT", "包商银行(信用卡)"), 
    CQB_DEBIT("CQB_DEBIT", "重庆银行(借记卡)"), 
    SDEB_DEBIT("SDEB_DEBIT", "顺德农商行(借记卡)"), 
    SZRCB_DEBIT("SZRCB_DEBIT", "深圳农商银行(借记卡)"), 
    HRBB_DEBIT("HRBB_DEBIT", "哈尔滨银行(借记卡)"), 
    BOCD_DEBIT("BOCD_DEBIT", "成都银行(借记卡)"), 
    GDNYB_DEBIT("GDNYB_DEBIT", "南粤银行(借记卡)"), 
    GDNYB_CREDIT("GDNYB_CREDIT", "南粤银行(信用卡)"), 
    GZCB_DEBIT("GZCB_DEBIT", "广州银行(借记卡)"), 
    GZCB_CREDIT("GZCB_CREDIT", "广州银行(信用卡)"), 
    JSB_DEBIT("JSB_DEBIT", "江苏银行(借记卡)"), 
    JSB_CREDIT("JSB_CREDIT", "江苏银行(信用卡)"),
    NBCB_DEBIT("NBCB_DEBIT", "宁波银行(借记卡)"), 
    NBCB_CREDIT("NBCB_CREDIT", "宁波银行(信用卡)"), 
    NJCB_DEBIT("NJCB_DEBIT", "南京银行(借记卡)"), 
    JZB_DEBIT("JZB_DEBIT", "晋中银行(借记卡)"), 
    KRCB_DEBIT("KRCB_DEBIT", "昆山农商(借记卡"), 
    LJB_DEBIT("LJB_DEBIT", "龙江银行(借记卡)"), 
    LNNX_DEBIT("LNNX_DEBIT", "辽宁农信(借记卡)"), 
    LZB_DEBIT("LZB_DEBIT", "兰州银行(借记卡)"), 
    WRCB_DEBIT("WRCB_DEBIT", "无锡农商(借记卡)"), 
    ZYB_DEBIT("ZYB_DEBIT", "中原银行(借记卡)"), 
    ZJRCUB_DEBIT("ZJRCUB_DEBIT", "浙江农信(借记卡)"), 
    WZB_DEBIT("WZB_DEBIT", "温州银行(借记卡)"), 
    XAB_DEBIT("XAB_DEBIT", "西安银行(借记卡)"), 
    JXNXB_DEBIT("JXNXB_DEBIT", "江西农信(借记卡)"), 
    NCB_DEBIT("NCB_DEBIT", "宁波通商银行(借记卡)"), 
    NYCCB_DEBIT("NYCCB_DEBIT", "南阳村镇银行(借记卡)"), 
    NMGNX_DEBIT("NMGNX_DEBIT", "内蒙古农信(借记卡)"), 
    SXXH_DEBIT("SXXH_DEBIT", "陕西信合(借记卡)"), 
    SRCB_CREDIT("SRCB_CREDIT", "上海农商银行(信用卡)"), 
    SJB_DEBIT("SJB_DEBIT", "盛京银行(借记卡)"), 
    SDRCU_DEBIT("SDRCU_DEBIT", "山东农信(借记卡)"), 
    SRCB_DEBIT("SRCB_DEBIT", "上海农商银行(借记卡)"), 
    SCNX_DEBIT("SCNX_DEBIT", "四川农信(借记卡)"), 
    QLB_DEBIT("QLB_DEBIT", "齐鲁银行(借记卡)"), 
    QDCCB_DEBIT("QDCCB_DEBIT", "青岛银行(借记卡)"), 
    PZHCCB_DEBIT("PZHCCB_DEBIT", "攀枝花银行(借记卡)"), 
    ZJTLCB_DEBIT("ZJTLCB_DEBIT", "浙江泰隆银行(借记卡)"), 
    TJBHB_DEBIT("TJBHB_DEBIT", "天津滨海农商行(借记卡)"), 
    WEB_DEBIT("WEB_DEBIT", "微众银行(借记卡)"), 
    YNRCCB_DEBIT("YNRCCB_DEBIT", "云南农信(借记卡)"), 
    WFB_DEBIT("WFB_DEBIT", "潍坊银行(借记卡)"), 
    WHRC_DEBIT("WHRC_DEBIT", "武汉农商行(借记卡)"), 
    ORDOSB_DEBIT("ORDOSB_DEBIT", "鄂尔多斯银行(借记卡)"), 
    XJRCCB_DEBIT("XJRCCB_DEBIT", "新疆农信银行(借记卡)"), 
    ORDOSB_CREDIT("ORDOSB_CREDIT", "鄂尔多斯银行(信用卡)"), 
    CSRCB_DEBIT("CSRCB_DEBIT", "常熟农商银行(借记卡)"), 
    JSNX_DEBIT("JSNX_DEBIT", "江苏农商行(借记卡)"), 
    GRCB_CREDIT("GRCB_CREDIT", "广州农商银行(信用卡)"), 
    GLB_DEBIT("GLB_DEBIT", "桂林银行(借记卡)"), 
    GDRCU_DEBIT("GDRCU_DEBIT", "广东农信银行(借记卡)"), 
    GDHX_DEBIT("GDHX_DEBIT", "广东华兴银行(借记卡)"), 
    FJNX_DEBIT("FJNX_DEBIT", "福建农信银行(借记卡)"), 
    DYCCB_DEBIT("DYCCB_DEBIT", "德阳银行(借记卡)"), 
    DRCB_DEBIT("DRCB_DEBIT", "东莞农商行(借记卡)"), 
    CZCB_DEBIT("CZCB_DEBIT", "稠州银行(借记卡)"), 
    CZB_DEBIT("CZB_DEBIT", "浙商银行(借记卡)"), 
    CZB_CREDIT("CZB_CREDIT", "浙商银行(信用卡)"), 
    GRCB_DEBIT("GRCB_DEBIT", "广州农商银行(借记卡)"), 
    CSCB_DEBIT("CSCB_DEBIT", "长沙银行(借记卡)"), 
    CQRCB_DEBIT("CQRCB_DEBIT", "重庆农商银行(借记卡)"), 
    CBHB_DEBIT("CBHB_DEBIT", "渤海银行(借记卡)"), 
    BOIMCB_DEBIT("BOIMCB_DEBIT", "内蒙古银行(借记卡)"), 
    BOD_DEBIT("BOD_DEBIT", "东莞银行(借记卡)"), 
    BOD_CREDIT("BOD_CREDIT", "东莞银行(信用卡)"), 
    BOB_DEBIT("BOB_DEBIT", "北京银行(借记卡)"), 
    BNC_DEBIT("BNC_DEBIT", "江西银行(借记卡)"), 
    BJRCB_DEBIT("BJRCB_DEBIT", "北京农商行(借记卡)"), 
    AE_CREDIT("AE_CREDIT", "AE(信用卡)"), 
    GYCB_CREDIT("GYCB_CREDIT", "贵阳银行(信用卡)"), 
    JSHB_DEBIT("JSHB_DEBIT", "晋商银行(借记卡)"), 
    JRCB_DEBIT("JRCB_DEBIT", "江阴农商行(借记卡)"),
    JNRCB_DEBIT("JNRCB_DEBIT", "江南农商(借记卡)"), 
    JLNX_DEBIT("JLNX_DEBIT", "吉林农信(借记卡)"), 
    JLB_DEBIT("JLB_DEBIT", "吉林银行(借记卡)"), 
    JJCCB_DEBIT("JJCCB_DEBIT", "九江银行(借记卡)"), 
    HXB_DEBIT("HXB_DEBIT", "华夏银行(借记卡)"), 
    HXB_CREDIT("HXB_CREDIT", "华夏银行(信用卡)"), 
    HUNNX_DEBIT("HUNNX_DEBIT", "湖南农信(借记卡) "),
    HSB_DEBIT("HSB_DEBIT", "徽商银行(借记卡)"), 
    HSBC_DEBIT("HSBC_DEBIT", "恒生银行(借记卡)"), 
    HRXJB_DEBIT("HRXJB_DEBIT", "华融湘江银行(借记卡)"), 
    HNNX_DEBIT("HNNX_DEBIT", "河南农信(借记卡)"), 
    HKBEA_DEBIT("HKBEA_DEBIT", "东亚银行(借记卡)"), 
    HEBNX_DEBIT("HEBNX_DEBIT", "河北农信(借记卡)"), 
    HBNX_DEBIT("HBNX_DEBIT", "湖北农信(借记卡)"), 
    HBNX_CREDIT("HBNX_CREDIT", "湖北农信(信用卡)"), 
    GYCB_DEBIT("GYCB_DEBIT", "贵阳银行(借记卡)"), 
    GSNX_DEBIT("GSNX_DEBIT", "甘肃农信(借记卡)"), 
    JCB_CREDIT("JCB_CREDIT", "JCB(信用卡)"), 
    MASTERCARD_CREDIT("MASTERCARD_CREDIT", "MASTERCARD(信用卡)"), 
    VISA_CREDIT("VISA_CREDIT", "VISA(信用卡)");
    
    private String value;
    private String name;
    
    private WxPayBank(String value, String name) {
        this.value = value;
        this.name = name;
    }
    
    public String getValue() {
        return value;
    }

    public String getName() {
        return name;
    }
    
}
